"""Offline regressions for the generated Gridctl cask validator."""

import importlib.util
import hashlib
from pathlib import Path
import re
import tempfile
import unittest


SPEC = importlib.util.spec_from_file_location(
    "validate_generated_cask", Path(__file__).with_name("validate_generated_cask.py")
)
validator = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(validator)
validation_errors = validator.validation_errors

REGRESSION_SPEC = importlib.util.spec_from_file_location(
    "check_goreleaser_cask", Path(__file__).with_name("check_goreleaser_cask.py")
)
regression = importlib.util.module_from_spec(REGRESSION_SPEC)
REGRESSION_SPEC.loader.exec_module(regression)


VALID_CASK = '''# This file was generated by GoReleaser. DO NOT EDIT.
cask "gridctl" do
  on_macos do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v1.2.3/gridctl_#{version}_darwin_amd64.tar.gz"
      sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v1.2.3/gridctl_#{version}_darwin_arm64.tar.gz"
      sha256 "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    end
  end
  on_linux do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v1.2.3/gridctl_#{version}_linux_amd64.tar.gz"
      sha256 "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v1.2.3/gridctl_#{version}_linux_arm64.tar.gz"
      sha256 "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
    end
  end

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gridctl"]
    end
  end

  version "1.2.3"
end
'''


class GeneratedCaskValidatorTests(unittest.TestCase):
    def assert_invalid(self, cask, diagnostic):
        self.assertTrue(
            any(diagnostic in error for error in validation_errors(cask)),
            validation_errors(cask),
        )

    def test_accepts_expected_postflight_steps(self):
        self.assertEqual([], validation_errors(VALID_CASK))

    def test_rejects_legacy_wrapper(self):
        legacy = VALID_CASK.replace("postflight_steps do", "postflight do")
        self.assert_invalid(legacy, "legacy postflight declaration")

    def test_rejects_duplicate_hooks(self):
        duplicate = VALID_CASK.replace(
            '  version "1.2.3"',
            VALID_CASK[VALID_CASK.index("  postflight_steps"):VALID_CASK.index('  version "1.2.3"')]
            + '  version "1.2.3"',
        )
        self.assert_invalid(duplicate, "exactly one postflight_steps")
        self.assert_invalid(duplicate, "exactly one xattr run step")

    def test_rejects_unguarded_xattr(self):
        guarded = '''  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gridctl"]
    end
  end
'''
        unguarded = '''  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gridctl"]
  end
'''
        unguarded = VALID_CASK.replace(guarded, unguarded)
        self.assert_invalid(unguarded, "macOS-gated xattr")

    def test_rejects_wrong_staged_path_token(self):
        wrong_token = VALID_CASK.replace("{{staged_path}}/gridctl", "#{staged_path}/gridctl")
        self.assert_invalid(wrong_token, "literal {{staged_path}}/gridctl")

    def test_rejects_missing_steps(self):
        start = VALID_CASK.index("  postflight_steps")
        end = VALID_CASK.index('  version "1.2.3"')
        missing = VALID_CASK[:start] + VALID_CASK[end:]
        self.assert_invalid(missing, "postflight_steps declaration")
        self.assert_invalid(missing, "xattr run step")

    def test_rejects_missing_platform_asset(self):
        missing = VALID_CASK.replace("_linux_arm64.tar.gz", "_linux_armv7.tar.gz")
        self.assert_invalid(missing, "production _linux_arm64.tar.gz asset URL")

    def test_rejects_nonproduction_asset_url(self):
        wrong = VALID_CASK.replace("https://github.com/gridctl/gridctl", "https://example.invalid", 1)
        self.assert_invalid(wrong, "production _darwin_amd64.tar.gz asset URL")

    def test_rejects_unresolved_goreleaser_template(self):
        unresolved = VALID_CASK.replace(
            '  version "1.2.3"', '  version "{{ .Version }}"'
        )
        self.assert_invalid(unresolved, "unresolved GoReleaser template")

    def test_fixture_preserves_production_cask_configuration(self):
        import yaml

        production_source = Path(".goreleaser.yaml").read_text()
        fixture = regression.fixture_config(
            regression.production_cask_config(production_source), Path("/tmp/dist")
        )
        production = yaml.safe_load(production_source)
        generated = yaml.safe_load(fixture)
        self.assertEqual(production["homebrew_casks"], generated["homebrew_casks"])
        self.assertTrue(generated["release"]["skip_upload"])

    def test_generated_archive_checksums_match_cask(self):
        cask = VALID_CASK
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary)
            for suffix in validator.ARCHIVE_SUFFIXES:
                archive = output / f"gridctl_1.2.3{suffix}"
                archive.write_bytes(suffix.encode())
                digest = hashlib.sha256(archive.read_bytes()).hexdigest()
                pattern = (
                    r'(url "[^"]+_#\{version\}' + re.escape(suffix)
                    + r'"\n\s*sha256 ")[0-9a-f]{64}'
                )
                cask = re.sub(pattern, rf"\g<1>{digest}", cask)
            self.assertEqual([], regression.archive_checksum_errors(cask, output))
            (output / "gridctl_1.2.3_linux_amd64.tar.gz").write_bytes(b"changed")
            self.assertEqual(
                ["generated cask checksum does not match gridctl_1.2.3_linux_amd64.tar.gz"],
                regression.archive_checksum_errors(cask, output),
            )

    def test_legacy_baseline_errors_are_exact(self):
        legacy = VALID_CASK.replace("postflight_steps do", "postflight do").replace(
            'run "/usr/bin/xattr",', 'system_command "/usr/bin/xattr",'
        ).replace("{{staged_path}}/gridctl", "#{staged_path}/gridctl")
        self.assertEqual(validator.LEGACY_BASELINE_ERRORS, validation_errors(legacy))


if __name__ == "__main__":
    unittest.main()
